# Generated by Django 2.1.2 on 2018-11-21 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_id', models.CharField(default='0', max_length=16)),
                ('name', models.CharField(default='Не указано', max_length=80)),
                ('surname', models.CharField(default='Не указано', max_length=80)),
                ('patronymic', models.CharField(default='Не указано', max_length=80)),
                ('room', models.CharField(default='Не указано', max_length=30)),
                ('age', models.DateField(null=True)),
                ('cause', models.CharField(default='Не указано', max_length=300)),
                ('gender', models.CharField(choices=[('Mужской', 'Мужской'), ('Женский', 'Женский')], default='Не указано', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PatientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_call', models.DateTimeField(null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myApp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_call', models.DateTimeField(null=True)),
                ('time_of_answer', models.DateTimeField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Patient')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_doctor', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('name', models.CharField(default='Не указано', max_length=80)),
                ('surname', models.CharField(default='Не указано', max_length=80)),
                ('patronymic', models.CharField(default='Не указано', max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=80)),
                ('color', models.CharField(default='Не указано', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='wing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.Wing'),
        ),
    ]
