# Generated by Django 2.1.2 on 2018-10-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=80)),
                ('surname', models.CharField(default='unknown', max_length=80)),
                ('patronymic', models.CharField(default='unknown', max_length=80)),
                ('room', models.CharField(default='unknown', max_length=30)),
                ('age', models.CharField(default='unknown', max_length=3)),
                ('cause', models.CharField(default='unknown', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
