# Generated by Django 2.1.2 on 2018-10-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20181030_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='wing',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
