# Generated by Django 2.1.2 on 2018-10-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20181030_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='z_id',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
