# Generated by Django 2.1.2 on 2018-11-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_patientlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='z_id',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
