# Generated by Django 2.1.2 on 2018-11-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20181102_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('Ж', 'Женский')], default='unknown', max_length=30),
        ),
    ]
