# Generated by Django 2.1.2 on 2018-11-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20181107_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Mужской', 'Мужской'), ('Женский', 'Женский')], default='unknown', max_length=30),
        ),
    ]
