# Generated by Django 2.1.2 on 2018-11-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20181107_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=80)),
                ('color', models.CharField(default='Не указано', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(default='Не указано', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cause',
            field=models.CharField(default='Не указано', max_length=300),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Mужской', 'Мужской'), ('Женский', 'Женский')], default='Не указано', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='Не указано', max_length=80),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patronymic',
            field=models.CharField(default='Не указано', max_length=80),
        ),
        migrations.AlterField(
            model_name='patient',
            name='room',
            field=models.CharField(default='Не указано', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='surname',
            field=models.CharField(default='Не указано', max_length=80),
        ),
        migrations.AlterField(
            model_name='patient',
            name='wing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Wing'),
        ),
    ]
