# Generated by Django 2.1.2 on 2018-11-07 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_auto_20181107_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='wing',
            field=models.ForeignKey(default='Не указано', on_delete=django.db.models.deletion.CASCADE, to='myApp.Wing'),
        ),
    ]
