# Generated by Django 2.1.2 on 2018-11-19 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_patientlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Patient'),
        ),
        migrations.AlterField(
            model_name='patientlog',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
