# Generated by Django 2.1.2 on 2018-11-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_auto_20181119_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlist',
            name='time_of_call',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patientlog',
            name='time_of_answer',
            field=models.DateTimeField(null=True),
        ),
    ]
