# Generated by Django 2.1.2 on 2018-11-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_auto_20181119_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.DateField(null=True),
        ),
    ]
