# Generated by Django 2.1.2 on 2018-11-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_auto_20181119_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='patronymic',
            field=models.CharField(default='Не указано', max_length=80),
        ),
    ]
